services:
  # Servicio Web (Flask App)
  - type: web
    name: medisoft-app
    env: python
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: medisoft-db
          property: connectionString
    healthCheckPath: /

databases:
  # Base de datos PostgreSQL
  - name: medisoft-db
    databaseName: medisoft_db
    user: medisoft_user
    plan: free

